FROM linuxserver/chromium:amd64-latest AS build

LABEL maintainer="wolkenschieber"
LABEL project_page="https://github.com/wolkenschieber/docker-chromium"

ENV TITLE=Chromium

COPY /policies /etc/chromium/policies

RUN \
    chmod -w /etc/chromium/policies/managed

FROM linuxserver/chromium:arm64v8-latest
COPY /policies /etc/chromium/policies